CREATE TABLE drama_catalogue(
    drama_id INT AUTO_INCREMENT PRIMARY KEY,
    image_filename VARCHAR(255) NOT NULL,
    title VARCHAR(100) NOT NULL,
    average_rating DECIMAL(3,2) NOT NULL,
    release_year INT NOT NULL CHECK (release_year >= 1900 AND release_year <= 2100),
    episodes TINYINT(2) NOT NULL,
    category VARCHAR(50) NOT NULL,
    original_network VARCHAR(50) NOT NULL,
    director VARCHAR(255) NOT NULL,
    screenwriter VARCHAR(255) NOT NULL,
    cast VARCHAR(255) NOT NULL, 
    description TEXT NOT NULL,
    image_url VARCHAR(2048) NOT NULL
);

CREATE TABLE catalogue_admin (
    account_id  INT(3) AUTO_INCREMENT PRIMARY KEY,
    username VARCHAR(16) NOT NULL,
    first_name VARCHAR(25) NOT NULL,
    last_name VARCHAR(25) NOT NULL, 
    email VARCHAR(255) NOT NULL,
    hashed_password VARCHAR(72) NOT NULL,
    profile_img VARCHAR(1024) DEFAULT NULL,
    date datetime DEFAULT current_timestamp(), 
    role VARCHAR(10) NOT NULL
);

CREATE TABLE user_rating (
    rating_id INT AUTO_INCREMENT PRIMARY KEY,
    account_id INT NOT NULL,
    drama_id INT NOT NULL,
    title VARCHAR(50) NOT NULL,
    rating TINYINT(1) NOT NULL CHECK (rating >= 0 AND rating <= 5),
    description TEXT,
    review_date DATETIME default current_timestamp(),
    FOREIGN KEY (account_id) REFERENCES catalogue_admin(account_id),
    FOREIGN KEY (drama_id) REFERENCES drama_catalogue(drama_id)
);

INSERT INTO catalogue_admin (username, hashed_password)
VALUES 
    ('admin', '$2y$10$2W3SA9vKsg0LMvAkgx8vteGIdIquXfWns3w6lfY37nMtL9sQ6Y0zK'),
    ('instructor', '$2y$10$k5Ux9iLpxMUCcdwrjEUlrOFZKZcHWOcljWtaxkYlDuCoHNXReqi/S')


INSERT INTO drama_catalogue(title, average_rating, release_year, episodes, category, original_network, director, screenwriter, cast, description, image_url)
VALUES 
    ('Mysterious Lotus Casebook',4.80,2023,40,'Mystery, Wuxia','iQiYi','Guo Hu, Ren Hai Tao','Liu Fang','Cheng Yi, Joseph Zeng Shunxi, Aero Xiao Shunyao','After a fierce battle 10 years ago, Li Xiang Yi who was the master of the Sigu Sect lives life as a countryside doctor Li Lian Hua. He accidentally encounters Fang Duo Bing, a passionate detective and his fierce enemy Di Fei Sheng to investigate many mystery cases. Finally, the three gradually come to forge a deep friendship.', 'https://mydramalist.com/photos/kAozjj_4'),
    ('Love Like the Galaxy',4.55,2022,56,'Historical, Mystery, Romance, Political','Tencent Video','Fei Zhen Xiang','Zou Yue, An Yi Mo','Leo Wu, Zhao Lu Si','The young Cheng Shao Shang had been left behind for 15 years because her parents had gone off for the war.  The feared war general and the foster son of the Emperor, Ling Bu Yi. In getting along with Ling Bu Yi, Cheng Shao Shang becomes involved in the mystery of Ling Bu Yi\'s family and identity by accident.', 'https://mydramalist.com/photos/q4PlK_4'),
    ('The Untamed',4.57,2019,50,'Mystery, Wuxia, Fantasy','Tencent Video','Steve Cheng, Chan Ka Lam','Deng Yao Yu, Yang Xia, Guo Guang Yun, Jing Ma','Xiao Zhan, Wang Yi Bo, Wang Zhuo Cheng','The series follows the adventures of two soulmate cultivators Wei Wu Xian and Lan Wang Ji who travel to solve a series of murder mysteries, eventually finding and defeating the true culprit.','https://mydramalist.com/photos/qOrz5'),
    ('Love Between Fairy and Devil',4.30,2022,36,'Comedy, Romance, Wuxia, Fantasy','iQiYi','Yi Zheng, Qian Jing Wu','Cao Xiao Tian, Bai Jin Jin','Yu Shu Xin, Dylan Wang, Zhang Ling He','The Chinese drama is adapted from the novel of the same name by Jiulu Feixiang, and tells the story of a sweet and sadistic love story caused by the accidental body exchange between the fairy Xia Lan Hua and the moon god Dongfang Qingcang.','https://mydramalist.com/photos/xJDEr_4'),
    ('Ultimate Note',4.30,2020,37,'Action, Adventure, Thriller, Mystery','iQiYi','Zou Xi, Wei Li Zhou','Zhang Yuan Ang, Tian Liang Liang','Joseph Zeng, Xiao Yu Liang, Cheng Fang Xu, Liu Yu Ning, Liu Yu Han, Hankiz Omar','Wu Xie, Zhang Qiling and Wang Pangzi continued their adventures to the ghost kingdom of the snakes. They discovered a mysterious lake which located the ancient Yao village underwater and in the end, they managed to arrive at the Zhang family\'s mansion which was their final destination, where the mystery behind all of this was eventually revealed one by one.', 'https://mydramalist.com/photos/prEne_4'),
    ('Love and Redemption',4.20,2020,59,'Romance, Wuxia, Drama, Fantasy','Mango TV','Yin Tao, Mai Guan Zhi','Liu Fang','Cheng Yi, Yuan Bing Yan','The drama is adapted from the novel of the same name by Shi Si Lang. It tells the story of Chu Xuan Ji, a girl born with an incomplete "sixth sense", and Yu Si Feng, a disciple of Lize Palace, who face the double pressure of love and conspiracy in a previous life, and work together to create a colourful fairy tale story.', 'https://mydramalist.com/photos/BoB65_4'),
    ('Lost You Forever',4.30,2023,39,'Romance, Wuxia, Drama, Fantasy','Tencent Video','Yang Huan, Zoe Qin','Wong Jing, Ye Chin','Yang Zi, Zhang Wan Yi, Deng Wei, Tan Jian Ci, Wang Hong Yi, Dai Lu Wa','In ancient times, when gods, goddesses, demons, and mythical creatures lived alongside humans, there were 3 mythical ruling kingdoms Xi Yan, Chen Rong and Hao Ling that each governed a region of the world. The story of Hao Ling Princess Xiao Yao and her life journey with Tushan Jing who is the future leader of the Tu Shan Clan; encounters Xiang Liu a nine-headed demon and reunites with her cousin, Xi Yan Prince Cang Xuan.','https://mydramalist.com/photos/1wOLbK_4'),
    ('The Blue Whisper',4.00,2022,42,'Romance, Wuxia, Fantasy','Youku','Chu Yui Bun, Gu Zhi Wei','Li Jing Ling','Dilraba Dilmurat, Ren Jia Lun','The Chinese drama is adapted from Jiulu Feixiang\'s novel "The Story of the Shark". It tells the story of Ji Yun He, a spiritual master and Chang Yi, a mermaid who break through their shackles, go through all kinds of difficulties and dangers, and finally become a family, working together to protect the common people.', 'https://mydramalist.com/photos/dqjKb_4'),
    ('Story of Kunning Palace',4.50,2023,38,'Historical, Romance, Drama, Fantasy','iQiYi','Chu Yui Bun, Francis Nam, Gu Zhi Wei','Shi Jing','Bai Lu, Zhang Ling He, Wang Xing Yue, Zhou Jun Wei, Liu Xie Ning','Jiang Xuening had gone to great lengths to become empress but was forced to commit suicide during a palace mutiny. Now, Jiang Xuening\'s dream I to get away from power and have control over her own life but her journey is still involved with the imperial.', 'https://mydramalist.com/photos/Z8gvy7_4'),
    ('Novoland: Pearl Eclipse',4.20,2021,48,'Romance, Wuxia, Fantasy','Tencent Video','Jin Sha, Yu Bo','Li Yan Qian, Zhang Lin Nan','Yang Mi, William Chan, Xu Kai Cheng, Chen Xiao Yun','During the Zheng dynasty in the vast ocean of Novoland, seeking for a magical pearl, and for this reason, a young girl Hai Shi lost her parents and her whole Yu coastal village. She met Fang Zhu - the first official of the imperial court, Hai Shi needed to pretend as a male and become Fang Zhu\'s disciple. When the emperor finds out that Hai Shi is a girl, he starts having feelings for her. Hai Shi will have to face her own feelings towards Fang Zhu and the emperor.', 'https://mydramalist.com/photos/QRwg7_4'),
    ('Go Go Squid',4.20,2019,41,'Comedy, Romance, Youth, Sports','iQiYi','Lee Ching Jung','Mo Bao Fei Bao','Yang Zi, Li Xian','A love story between Tong Nian who is a PhD computer science student and Han Shang Yan who is older than her and a legendary e-sport gamer.', 'https://mydramalist.com/photos/RAVoo'),
    ('Hidden Love',4.50,2023,25,'Comedy, Romance, Youth','Youku','Lee Ching Jung','Shen Fei Xian','Zhao Lu Si, Chen Zhe Yuan','Shang Zhi falls in love with Duan Jia Xu who is the best friend of her older brother. But they lost contact with each other when Duan Jia Xu graduated from university and moved back to his hometown. Until Shang Zhi got into the university in the city he is in they finally met again, and during their day-to-day intimate and close interaction, they slowly fall in love.', 'https://mydramalist.com/photos/x4vJO3_4'),
    ('Forever and Ever',4.00,2021,30,'Romance, Drama','iQiYi','Shen Yang, Ben Fang','Mo Bao Fei Bao','Ren Jia Lun, Bai Lu','The story is about Shi Yi, a gentle pleasant and low-key industry\'s top voice actress who ran into the elegant returnee chemistry professor Zhou Sheng Chen at the airport. They gradually develop a mutual understanding in getting along with each other and join hands to preserve traditional craftsmanship and overcome many storms as they decide to accompany each other for the rest of their lives.', 'https://mydramalist.com/photos/eNO4E_4'),
    ('Go Ahead',4.10,2020,46,'Comedy, Romance, Drama, Melodrama','Mango TV','Ding Zi Guang','Wang Xiong Cheng, Shui Qian Mo','Tan Song Yun, Song Wei Long, Zhang Xin Cheng, Tu Song Yan, Zhang Xi Lin','Growing up together in dysfunctional households, three individuals who are unrelated by blood treat each other like family as they yearn for the love that they cannot find at home. They got separated for nine years. After the three are united, they have to face their complicated family past and it becomes a shadow that constantly lingers on them.', 'https://mydramalist.com/photos/exXvQ_4'),
    ('Moonlight',4.20,2021,36,'Business, Comedy, Romance, Drama','iQiYi','Elson Chang','Zhu Qi, Qiu Ting','Yu Shu Xin, Ding Yu Xi, Yang Shi Ze, Ma Yin Yin','Chu Li successfully got into her dream company Yuan Yue Publishing House as the editor. However, she has to face with many challenging as her major at university is financing. Her first edited novel is from Zhou Chuan, he is known as a gentle as a jade while for her, he is really not. The two are immediately at odds, with Zhou Chuan later discovering that Chu Li is his online friend - Monkey.', 'https://mydramalist.com/photos/1Pv03_4'),
    ('When I fly Towards You',4.50,2023,24,'Comedy, Romance, Youth','Youku','Mao De Shu','Yue An, Tao Kai Xin','Zhou Yi Ran, Zhang Miao Yi','On the first day of school, Su Zai Zai sees a classmate and falls in love with Zhang Lu Rang at first sight. He is rude to everyone around him as his own family is treated unfairly by him and his younger brother. However, his life changes when he meets Su Zai Zai who makes him understand the meaning of self and slowly begins to understand how to plan his life. Both slowly developed feelings for each other and gained happiness together.', 'https://mydramalist.com/photos/1wOO83_4'),
    ('She and Her Perfect Husband',3.90,2022,40,'Law, Romance','Tencent Video','Lin Yan','Zhu Li','Yang Mi, Xu Kai, Li Ze Feng, Tang Jing Mei, Wang Zi Xuan','The love story about Qin Shi, an elite lawyer and Yang Hua, a senior otaku who get married by accident, find true love in the process and create a beautiful and happy life together.', 'https://mydramalist.com/photos/roWAp_4'),
    ('Hi Venus',4.20,2022,24,'Comedy, Romance, Life','Youku','Wang Zheng','Wang Xiong Cheng','Joseph Zeng, Liang Jie, Zhou Zi Han, Li Lin Fei','A pediatrician and the new hospital director start off on the wrong foot due to a large misunderstanding; when they are forced to work closely, the truth is revealed and their love story start to begin.', 'https://mydramalist.com/photos/QzvQW_4'),
    ('Meet Yourself',4.20,2023,40,'Romance, Life, Drama','Mango TV','Ding Zi Guang','Wang Xiong Cheng, Shui Qian Mo','Crystal Liu, Li Xian','After the death of her best friend, Xu Hongdou decided to quit her job and have herself a vacation in Dali, Yunnan. She meets Zhi Yao who is a local boy with an aim to develop the area to give the people a better life without needing to make a living far away from home. Each of them has their own heartaches and challenges to face.', 'https://mydramalist.com/photos/dPk5e_4'),
    ('Medical Examiner Dr Qin',4.30,2016,20,'Mystery, Drama, Medical','Sohu TV','Xu Ang','Yang Zhe','Zhang Ruo Yun, Jiao Jun  Yan, Li Xian','Qin Ming doesn\'t trust his new assistant Li Da Bao but later he finds that she has very good reasoning and observation capabilities, and has a very sensitive sense of smell. The critical Qin decides to have her on board. Later on, Qin along with his detective friend Lin Tao and assistant Li Da Bao uncover a variety of bizarre cases.', 'https://mydramalist.com/photos/REgPx_4'),
    ('Guardian',4.20,2018,40,'Thriller, Mystery, Fantasy','Youku','Zhou Yuan Zhou, Gao Han, Xie Yi Hang, Gu Zhi Wei','Ma Chun Tao, Fu Si Zhen, Han Jing','Bai Yu, Zhu Yi Long','A world beyond scientific understanding with a group of passionate adults trying to solve cases done by such forces. Zhao Yun Lan and Shen Wei are tasked with upholding peace between underworld dwellers and humans, and the story will focus on their friendship that transcends past and present lifetimes.', 'https://mydramalist.com/photos/QpyE6'),
    ('Under the Skin',4.00,2022,20,'Thriller, Mystery','iQiYi','Xing Jian Jun','Wu Yao, Zhang Min, Jia Dong Yan','Tan Jian Ci, Jin Shi Jia','Due to the incident five years ago, Shen Yi, a young painter caused the death of a detective unknowingly. In the present day, he joins the police as a sketch artist to solve the case. He was partnered with Du Cheng who despises him for what happened 5 years prior. Overtime, they become closer and together find out the secret about the case that has haunted them for the past five years.', 'https://mydramalist.com/photos/0LODK_4'),
    ('Truth',3.90,2021,32,'Thriller, Mystery, Law, Drama','Youku','Li Yifan','Chu Chu','Chen Xing Xu, Cass Gai','Lin Lan and Lin Yuan Hao, prosecutors from the Criminal Procuratorate of the Jianghai City People, were appointed to form a crew. They use superior strategies to break the bottleneck of zero confession cases which are tough to resolve.', 'https://mydramalist.com/photos/dD8nD_4'),
    ('The Lost Tomb 2',4.20,2019,40,'Action, Adventure, Mystery, Supernatural','Tencent Video','Roger Lau','Bai Yi Cong','Neo Hou, Cheng Yi, Zhang Bo Yu, Li Man','The group of heroes is pulled into another tomb-raiding expedition that takes them beneath the sea. In an ancient Ming Dynasty ship, they encounter monstrous createures and puzzling traps. ', 'https://mydramalist.com/photos/wnnJ1'),
    ('My Roommate is a Detective',4.00,2020,36,'Thriller, Historical, Mystery, Comedy','iQiYi','Zhang Wei Ke','Hu Yue','Hu Yi Tian, Leon Zhang, Xiao Yan','Set in the mid-1920s, a young police officer named Qiao Chu Sheng is on the trail of a devious killer. Round up the team with Bai Yo Ning - a female reporter for a daily newspaper and Lu Yao - a brilliant young man who recently returned from studying in Great Britain. This trio will form a small detective squad that specializes in solving strange and unsettling murder mysteries.', 'https://mydramalist.com/photos/274EE'),
    ('You Are My Glory',4.50,2021,32,'Comedy, Romance, Life, Drama','Tencent Video','Wang Zhi','Gu Man','Yang Yang, Dilraba Dilmurat','A love story about an aerospace engineer Yu Tu and the shining star Qiao Jing Jing. A decision to start gaming in order to save her endorsement deal brings her face to face with an old crush. As they grow closer, the two forge ahead to become each other\'s glory', 'https://mydramalist.com/photos/jJVmO_4'),
    ('My Journey to You',4.30,2023,24,'Romance, Wuxia, Drama, Fantasy','iQiYi','Luo Luo','Edward Guo','Yu Shu Xin, Zhang Ling He, Ryan Cheng, Lu Yu Xiao','The series tells the story of Yun Wei Shan, a spy longing for freedom, who infiltrates the palace to complete a mission. Within the eerie and mysterious palace, she encounters love and friendship, embarks on a journey of self-discovery.', 'https://mydramalist.com/photos/RBeOER_4'),
    ('Till the End of the Moon',4.30,2023,40,'Romance, Wuxia, Fantasy','Youku','Kuk Kok Leung','He Fang, Luo Xuan','Luo Yun Xi, Bai Lu','An immortal, Li Susu is destined to time-travel 500 years back to prevent the death of a hostage prince to stop his transformation into the Devil god, who destroys four continents and three realms. Will secrets of time and fate deter her?', 'https://mydramalist.com/photos/Xd23Pd_4'),
    ('Back from the Brink',4.20,2023,40,'Romance, Wuxia, Drama, Fantasy','Youku','Sam Ho, Zeng Xiao Yu, Cheng Lu','Wang Ruo Ke','Neo Hou, Zhou Ye, Yang Rong, Riley Wang, Chen Xi Yu','Based on the novel of the same name by Jiulu Feixiang, twenty years ago, Tianyao\'s bones and tendons were torn out by his lover Suying, the Sect Leader of the Guanghan Sect. She sealed various parts of his body away with the powers of five elements. By chance, Tianyao\'s soul escaped the seal yen year ago.', 'https://mydramalist.com/photos/wJjmNk_4');

ALTER TABLE drama_catalogue 
ADD funfacts VARCHAR(255)

UPDATE drama_catalogue SET funfacts = "It hit 10,000 heat index on iQIYI on Aug 9, the same day as the fast track finale. Many of the members shared dance videos to celebrate." WHERE title = "Mysterious Lotus Casebook";
UPDATE drama_catalogue SET funfacts = "The original novel is a time-travel story where the wild unruly female lead from the modern day ends up in ancient times." WHERE title = "Love Like the Galaxy";
UPDATE drama_catalogue SET funfacts = "Before filming, the cast trained for 15 days to learn action choreography and Carman Lee makes a cameo in the drama." WHERE title = "The Untamed";
UPDATE drama_catalogue SET funfacts = "The novel is also known online as Demon King. Before the live-action, it had already been adapted into manhua and heat index of 10,500 on iQIYI for its finale." WHERE title = "Love Between Fairy and Devil";
UPDATE drama_catalogue SET funfacts = "It is the third installment in the Daomu Biji drama adaptations by H&R Century Pictures. Each season features a different cast playing the same characters." WHERE title = "Ultimate Note";
UPDATE drama_catalogue SET funfacts = "Due to popular demand from fans to delay the pay for episodes feature which was supposed to start on Aug 20, it was delayed by one week." WHERE title = "Love and Redemption";
UPDATE drama_catalogue SET funfacts = "Filming wrapped after 6 months (182 days) on September 25, 2022. And it hit a 31,000 heat index on Tencent after 2 days of premiere." WHERE title = "Lost You Forever";
UPDATE drama_catalogue SET funfacts = "It exceeded the 10,000 heat index on Youku 27 days after the premiere. And it is Youku's first drama in 2022 to cross 10,000." WHERE title = "The Blue Whisper";
UPDATE drama_catalogue SET funfacts = "The scheduled premiere on May 19, 2023, was postponed citing technical issues.It is among the dramas that hit a 10,000 heat index on iQIYI and crossed 10,100 by the fast-track finale on November 25, 2023." WHERE title = "Story of Kunning Palace";
UPDATE drama_catalogue SET funfacts = "It is the third collaboration between Yang Mi and Willliam Chan after Sword of Legends and L.O.R.D. Legend of Ravaging Dynasties." WHERE title = "Novoland: Pearl Eclipse";
UPDATE drama_catalogue SET funfacts = "The original novel, Stewed Squid With Honey, was published on November 25, 2014. It is the first to be adapted to a drama and the third book in the trilogy by author-screenwriter Mo Bao Fei Bao." WHERE title = "Go Go Squid";
UPDATE drama_catalogue SET funfacts = "It exceeded 10,000 popularity points on Youku 30 hours after premiere." WHERE title = "Hidden Love";
UPDATE drama_catalogue SET funfacts = "Some speculate that the novel was made into two dramas in order to avoid censorship by skirting around the theme of rebirth. In the novel, the female lead, Shi Yi, has memories of her past life when her heart belonged to Zhou Shengchen." WHERE title = "Forever and Ever";
UPDATE drama_catalogue SET funfacts = "The Chinese title for Go Ahead translates to In the Name of the Family." WHERE title = "Go Ahead";
UPDATE drama_catalogue SET funfacts = "Filming lasted three months from October 10, 2020, to January 6, 2021. It is part of iQIYI's "Sweet On" dramas." WHERE title = "Moonlight";
UPDATE drama_catalogue SET funfacts = "It was announced that shooting was suspended beginning September 2021 due to the pandemic." WHERE title = "When I fly Towards You";
UPDATE drama_catalogue SET funfacts = "Yang Mi and Xu Kai have an age difference of nine years. She and Her Perfect Husband follows the \"jie di lian\" trope that pairs an older woman with a younger man." WHERE title = "She and Her Perfect Husband";
UPDATE drama_catalogue SET funfacts = "Time Flies and You Are Here stars Joseph Zeng and Liang Jie reunite for their second drama together. And it is from the creators of Find Yourself, Go Ahead and The Day of Becoming You" WHERE title = "Hi Venus";
UPDATE drama_catalogue SET funfacts = "The Chinese  title translates to, \'Go to a place where there\'s wind.' The drama was shot in Dali, Yunnan. It is Crystal Liu\'s first time headlining a modern drama as she often stars in period dramas." WHERE title = "Meet Yourself";
UPDATE drama_catalogue SET funfacts = "It is produced by Sohu and Booky Pictures and received praise for its one of a kind premise that is not often seen in c-dramas. Many gory and brutal scenes were depicted in vivid detail." WHERE title = "Medical Examiner Dr Qin";
UPDATE drama_catalogue SET funfacts = "The source novel is a BL novel that follows the relationship between the two male leads." WHERE title = "Guardian";
UPDATE drama_catalogue SET funfacts = "Jin Shijia takes a special starring role. Qin Hailu and Fang Zibin make special appearances." WHERE title = "Under the Skin";
UPDATE drama_catalogue SET funfacts = "Filming lasted 130 days while post-production took 120 days." WHERE title = "Truth";
UPDATE drama_catalogue SET funfacts = "It has hit 100 million views 15 hours after its premiere. On June 19, 2018, the drama hit 1 billion views two weeks after its premiere." WHERE title = "The Lost Tomb 2";
UPDATE drama_catalogue SET funfacts = "Filming took place in Shanghai." WHERE title = "My Roommate is a Detective";
UPDATE drama_catalogue SET funfacts = "Due to billing order being a sensitive issue, it was indicated that the cast names are ordered by age with Yang Yang who was born in 1991 listed first before Dilireba who is born in 1992." WHERE title = "You Are My Glory";
UPDATE drama_catalogue SET funfacts = "Having done movies in the past, it is novelist-turned-director Guo Jingming\'s first time directing a TV series." WHERE title = "My Journey to You";
UPDATE drama_catalogue SET funfacts = "Till the End of the Moon achieved the highest reservations (>5 million) on Youku 1 hour before the premiere. It has become the fastest drama to exceed 10,000 popularity points on Youku in just 29 hours since it premiered." WHERE title = "Till the End of the Moon";
UPDATE drama_catalogue SET funfacts = "Neo Hou Minghao and Zhou Ye star in their first xianxia romance." WHERE title = "Back from the Brink";
UPDATE drama_catalogue SET funfacts = "It is Liu Shishi's comeback to the historical genre since the 2017 series Lost Love in Times. And it is Liu Yuning's first time playing the male lead in a historical drama after playing the second lead in several dramas." WHERE title = "A Journey to Love";
